#:schema https://raw.githubusercontent.com/cloudflare/wrangler2/main/packages/wrangler/config-schema.json
name = "wbds"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[vars]
# Put your public Supabase keys here
NEXT_PUBLIC_SUPABASE_URL = "https://tsytbdnbevscxhrcccvq.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzeXRiZG5iZXZzY3hocmNjY3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyODQ2MTgsImV4cCI6MjA4Mzg2MDYxOH0.LcVorouHvEugFR4t_bsYzpFNRNzovuRGZBAAd59-qpc"
NODE_VERSION = "20"
